Repository paytrail/documentation, pull requests merged in 2020-05, with the labels that each got.

#14 Add section about paytrail/module to REST documentation
  content/legacy/rest-interface/_index.en.md
  content/legacy/rest-interface/php.md
Labels: documentation, enhancement

#16 Add working PHP example to Merchant API authentication
  content/merchant-api/v1/accessing.md
Labels: documentation, enhancement

#21 Improvements to the Best Practices content
  content/best-practices/_index.en.md
  content/best-practices/requirements.md
Labels: enhancement

#36 Move price to correct place in REST interface and add supported payment methods for sales channel
  content/legacy/rest-interface/payment-creation.md
  content/sales-channels/fields.md
Labels: bug
